version: "3.9"
services:
  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: player
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/my_sql/
    healthcheck:
      test: [ "CMD-SHELL", "mysql --user=root --password=root --execute 'USE player;'" ]
      interval: 2s
      retries: 30
      timeout: 60s
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8080:8080"
    environment:
      - YOUR_GITHUB_CLIENT_ID=${YOUR_GITHUB_CLIENT_ID}
      - YOUR_GITHUB_CLIENT_SECRET=${YOUR_GITHUB_CLIENT_SECRET}
      - YOUR_AWS_S3_BUCKETS_TRACKS=${YOUR_AWS_S3_BUCKETS_TRACKS}
      - YOUR_AWS_CREDENTIALS_ACCESS_KEY=${YOUR_AWS_CREDENTIALS_ACCESS_KEY}
      - YOUR_AWS_CREDENTIALS_SECRET_KEY=${YOUR_AWS_CREDENTIALS_SECRET_KEY}
      - YOUR_SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/player
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "3000:3000"
volumes:
  db_data:
