spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/player
    username: nellshark
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
amazon:
  bucket:
    name: ${AMAZON_BUCKET_NAME_TRACKS}
  credentials:
    access-key: ${AMAZON_CREDENTIALS_ACCESS_KEY}
    secret-key: ${AMAZON_CREDENTIALS_SECRET_KEY}
