spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${YOUR_GITHUB_CLIENT_ID}
            clientSecret: ${YOUR_GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/player
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
aws:
  region: eu-north-1
  s3:
    buckets:
      # noinspection SpringBootApplicationYaml
      tracks: ${YOUR_AWS_S3_BUCKETS_TRACKS}
  credentials:
    access-key: ${YOUR_AWS_CREDENTIALS_ACCESS_KEY}
    secret-key: ${YOUR_AWS_CREDENTIALS_SECRET_KEY}

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"
  allowed-credentials: true
  exposed-headers: "*"
