spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/player
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true

amazon:
  s3:
    buckets:
      tracks: ${AMAZON_S3_BUCKETS_TRACKS}

  credentials:
    access-key: ${AMAZON_CREDENTIALS_ACCESS_KEY}
    secret-key: ${AMAZON_CREDENTIALS_SECRET_KEY}
