spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/player
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
amazon:
  s3:
    buckets:
      tracks: music-tracks
    region: eu-north-1
  credentials:
    access-key: ${AMAZON_CREDENTIALS_ACCESS_KEY}
    secret-key: ${AMAZON_CREDENTIALS_SECRET_KEY}

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"
  allowed-credentials: true
  exposed-headers: "*"
